services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_started
    volumes: # need to understand this 
      - ./backend:/app
      - ./storage:/app/storage
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U copilot_app -d copilot_db"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    env_file:
      - .env
    volumes:
      - qdrant_data:/qdrant/storage
  
volumes:
  postgres_data:
  qdrant_data:
    
