"""modified repo_symbols, repo_imports, repo_files tables

Revision ID: 76063d517dbb
Revises: e8de22472854
Create Date: 2026-09-05 19:21:09.979881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76063d517dbb'
down_revision: Union[str, Sequence[str], None] = 'e8de22472854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repository_imports', 'language',
               existing_type=postgresql.ENUM('PYTHON', 'JAVASCRIPT', 'TYPESCRIPT', 'JAVA', 'GO', 'RUST', 'CPP', 'C', 'CSHARP', 'PHP', 'RUBY', 'SWIFT', 'KOTLIN', name='importlanguage'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repository_imports', 'language',
               existing_type=postgresql.ENUM('PYTHON', 'JAVASCRIPT', 'TYPESCRIPT', 'JAVA', 'GO', 'RUST', 'CPP', 'C', 'CSHARP', 'PHP', 'RUBY', 'SWIFT', 'KOTLIN', name='importlanguage'),
               nullable=True)
    # ### end Alembic commands ###
