"""added repository_chunk.py orm model

Revision ID: 951950bf89a4
Revises: dbc79e5e822b
Create Date: 2026-09-06 13:15:48.794729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951950bf89a4'
down_revision: Union[str, Sequence[str], None] = 'dbc79e5e822b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('repository_branch_id', sa.String(), nullable=False),
    sa.Column('repository_file_id', sa.String(), nullable=False),
    sa.Column('symbol_id', sa.String(), nullable=True),
    sa.Column('provider', sa.Enum('JCODE', 'SYMLENS', 'TREE_SITTER', name='chunkprovider'), nullable=False),
    sa.Column('chunk_type', sa.Enum('FILE', 'CLASS', 'FUNCTION', 'METHOD', name='chunktype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_branch_id'], ['repository_branches.id'], ),
    sa.ForeignKeyConstraint(['repository_file_id'], ['repository_files.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['repository_symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_file_id', 'symbol_id', 'chunk_type', name='uq_repo_chunk_file_symbol_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_chunks')
    # ### end Alembic commands ###
