"""repository_imports and repository_symbols added along with a column addition in repository_files

Revision ID: db7e504abf92
Revises: 
Create Date: 2026-09-05 12:53:43.504485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7e504abf92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_files', sa.Column('parse_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'SKIPPED', name='parsestatus'), nullable=False))
    op.add_column('repository_files', sa.Column('parse_error', sa.Text(), nullable=True))
    op.add_column('repository_files', sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_files', 'parsed_at')
    op.drop_column('repository_files', 'parse_error')
    op.drop_column('repository_files', 'parse_status')
    # ### end Alembic commands ###
